web/router.ex
defmodule Parko.Router do
  use Parko.Web, :router

  def guardian_current_user(conn,_) do
    Plug.Conn.assign(conn, :current_user, Guardian.Plug.current_resource(conn))
  end
 
  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Parko.Authentication, repo: Parko.Repo
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource  
    plug Corsica, origins: "*", allow_headers: ["content-type", "authorization"]
  end

  pipeline :auth_api do
    plug Guardian.Plug.EnsureAuthenticated, handler: Parko.LoginsessionAPIController    
  end


  scope "/", Parko do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/parks", ParkController
    resources "/bookings", BookingController
    resources "/points", PointController
    resources "/payments", PaymentController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/sessions/:id", SessionController, :delete
  end
  
  # Other scopes may use custom stacks.
  scope "/api", Parko do
     pipe_through :api
     post "/parking_find", ParkingApiController, :find
     post "/parking_book", ParkingApiController, :book
     post "/parking_elapse", ParkingApiController, :elapse
     post "/parking_finish", ParkingApiController, :finish
     post "/parking_extend", ParkingApiController, :extend
     post "/list_parking", ParkingApiController, :list_bookings
     post "/list_payments", ParkingApiController, :list_payments
     post "/loginsession", LoginsessionAPIController, :create
     get "/payments/:id", PaymentAPIController, :show
  end
  scope "/api", Parko do
    pipe_through [:api, :auth_api]
    delete "/loginsession/:id", LoginsessionAPIController, :delete
  end
end

web/views/layout_view.ex
defmodule Parko.LayoutView do
  use Parko.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

     <title>Hello Parko!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>

  <body>
    


     <!--  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>-->
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>                        
                    </button>
                    <a class="navbar-brand" href="/">Park Me</a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                <%= if @conn.assigns.current_user do %>
                    <ul class="nav navbar-nav" v-if="username">
                        <li class="active"><a href = "#/bookings"> My Parkings </a></li>
                    </ul>
                    <ul class="nav navbar-nav" v-if="username">
                        <li class="active"><a href = "#/payments">My Payments </a></li>
                    </ul>
                  <% else %>
                   <% end %> 
                    <ul class="nav navbar-nav navbar-right">
                         <%= if @conn.assigns.current_user do %>
                                <li class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Hi <span id = "user_id"><%= @conn.assigns.current_user.username %> </span> <span class="glyphicon glyphicon-user"><span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                         <li><%= link "Log out", to: session_path(@conn, :delete, @conn.assigns.current_user)%></li>
                                        <li><a href="#"><span class="glyphicon glyphicon-setting"></span>Setting</a></li>
                                    </ul>
                                </li>
                                <% else %>
                                <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                                <li> <%= link "Log in", to: session_path(@conn, :new) %></li>
                                <% end %>


                            
                    </ul>
                </div>
            </div>
        </nav>
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="//maps.googleapis.com/maps/api/js?key=<%= Application.get_env(:parko, :gmaps_api_key) %>"></script> 
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>